// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var SomeModuleBs = require("../src/SomeModule.bs");

console.log("# ------------- About timeouts");

var t = setTimeout((function (param) {
        console.log("Timeout occured! - from a raw javascript");
        return /* () */0;
      }), 3000);

console.log("# ------------- About bs.scope");

console.log("Length of ancestorOrigins = " + String(window.location.ancestorOrigins.length));

console.log("# ------------- About random");

var rand_val = Math.random();

console.log("Random value = " + rand_val.toString());

console.log("# ------------- About modules");

console.log("Some id = " + SomeModuleBs.some_id.toString());

console.log("# ------------- The End.");

exports.t = t;
exports.rand_val = rand_val;
/*  Not a pure module */
