// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("bs-platform/lib/js/js_dict.js");
var External_js = require("../external_js");
var SomeModuleBs = require("../src/SomeModule.bs");

console.log("# ------------- About timeouts");

var t = setTimeout((function (param) {
        console.log("Timeout occured! - from a raw javascript");
        return /* () */0;
      }), 3000);

console.log("# ------------- About bs.scope");

console.log("Length of ancestorOrigins = " + String(window.location.ancestorOrigins.length));

console.log("# ------------- About random");

var rand_val = Math.random();

console.log("Random value = " + rand_val.toString());

console.log("# ------------- About modules");

console.log("Some id = " + SomeModuleBs.some_id.toString());

console.log("# ------------- About dict");

var some_map = { };

some_map["John"] = 66;

console.log(some_map);

console.log("# ------------- About external.js");

var match = External_js.eid;

if (match == null) {
  console.log("eid not found");
} else {
  console.log("eid = " + match.toString());
}

var match$1 = Js_dict.get(External_js.peopleAge, "John");

if (match$1 !== undefined) {
  console.log("John is " + String(match$1));
} else {
  console.log("John can't be found");
}

console.log("# ------------- About objects");

function getPerson(prim) {
  return External_js.getPerson();
}

console.log(External_js.getPerson());

console.log("# ------------- The End.");

exports.t = t;
exports.rand_val = rand_val;
exports.some_map = some_map;
exports.getPerson = getPerson;
/*  Not a pure module */
